[workspace]

members = [
    "01/t",
    "02/t",
    "02/t2",
    "03/t",
    "04/t",
    "04/tb",
    "05/t",
    "06/t",
    "06/b",
    "07/a",
    "07/b",
    "08/a",
    "08/b",
    "09/a",
    "10/a",
]