[workspace]

members = [
    "01/t",
    "02/t",
    "02/t2",
    "03/t",
    "04/t",
    "04/tb",
    "05/t",
    "06/t",
    "06/b",
    "07/a",
    "07/b",
    "08/a",
    "08/b",
    "09/a",
    "10/a",
    "10/b",
    "12/a",
    "12/b",
    "13/a",
    "14/a",
    "15/a",
    "15/b",
    "16/a",
    "16/b",
    "17/a",
    "18/a",
    "19/a",
    "19/b",
    "20/a",
    "20/b",
]